Repository dnsimple/terraform-provider-dnsimple, pull requests merged in 2020-10, with the labels that each got.

#30 Email forward resource
  dnsimple/import_dnsimple_email_forward_test.go
  dnsimple/provider.go
  dnsimple/resource_dnsimple_email_forward.go
  dnsimple/resource_dnsimple_email_forward_test.go
  dnsimple/resource_dnsimple_record_test.go
  website/docs/index.html.markdown
  website/docs/r/email_forward.html.markdown
Labels: documentation, enhancement, size/XL

#12 Adding sandbox flag
  dnsimple/config.go
  dnsimple/provider.go
  dnsimple/provider_test.go
Labels: enhancement, size/S

#31 CHANGELOG: Fix link to `dnsimple_email_forward` PR
  CHANGELOG.md
Labels: size/XS
