Repository dnsimple/terraform-provider-dnsimple, pull requests merged in 2025-03, with the labels that each got.

#254 Remove terraform-plugin-mux dependency
  go.mod
  go.sum
  main.go
Labels: enhancement

#265 Bump to use Go 1.24.1
  .github/workflows/test.yml
  go.mod
  go.sum
  internal/framework/resources/domain_delegation_resource_test.go
  tools/sweep/main.go
Labels: dependencies

#264 Bump dnsimple-go to v4.0.0
  go.mod
  go.sum
  internal/framework/common/provider.go
  internal/framework/common/zone_record_cache.go
  internal/framework/common/zone_record_cache_test.go
  internal/framework/datasources/registrant_change_check_data_source.go
  internal/framework/provider/provider.go
  internal/framework/resources/contact_resource.go
  internal/framework/resources/domain_delegation_resource.go
  internal/framework/resources/domain_ds_record_resource.go
  internal/framework/resources/domain_resource.go
  internal/framework/resources/email_forward_resource.go
  internal/framework/resources/lets_encrypt_certificate_resource.go
  internal/framework/resources/provider_helpers_test.go
  internal/framework/resources/registered_domain/common.go
  internal/framework/resources/registered_domain/create.go
  internal/framework/resources/registered_domain/read.go
  internal/framework/resources/registered_domain/resource_test.go
  internal/framework/resources/registered_domain/update.go
  internal/framework/resources/zone_record_resource.go
  internal/framework/resources/zone_record_resource_test.go
  internal/framework/resources/zone_resource.go
  internal/framework/test_utils/utils.go
  internal/framework/utils/utils.go
  tools/sweep/main.go
Labels: dependencies, task
